from __future__ import annotations

import copy

from skfolio.optimization import NestedClustersOptimization
from skfolio.prior import BasePrior
from sklearn.base import clone
from sklearn.pipeline import Pipeline


def _safe_clone(estimator):
    """Clone an estimator safely, falling back to deepcopy for non-sklearn objects."""
    if estimator is None:
        return None
    try:
        return clone(estimator)
    except TypeError:
        return copy.deepcopy(estimator)


class StrategyBuilder:
    """Assembles skfolio-compatible pipeline estimators for portfolio optimisation.

    Acts as a fluent factory for sklearn.pipeline.Pipeline objects and
    NestedClustersOptimization ensembles. Consumes pre-selection transformers,
    cross-sectional scalers, a prior, and an optimizer, then stitches them
    into a single leak-proof estimator.

    Prefect Compatibility: All build_*() methods are pure functions of
    internal queue state and return serialisable estimator objects.

    Parameters
    ----------
    constraints : list[str] or None, optional
        Linear constraint strings generated by ConstraintBuilder.build().
        Example: ["core >= 0.50", "satellite <= 0.20"]. Default is None
        (unconstrained strategy).
    prior : BasePrior or None, optional
        A configured skfolio prior object from PriorSynthesiser.
        If None, the optimizer uses its own internal default prior.

    Raises
    ------
    TypeError
        If constraints is not a list of strings, or if prior is not a BasePrior.
    """

    def __init__(
        self,
        constraints: list[str] | None = None,
        prior: BasePrior | None = None,
    ) -> None:
        if constraints is not None:
            if not isinstance(constraints, list):
                raise TypeError("constraints must be a list.")
            if not all(isinstance(c, str) for c in constraints):
                raise TypeError("All constraints must be strings.")
            self.constraints = list(constraints)
        else:
            self.constraints = []

        if prior is not None and not isinstance(prior, BasePrior):
            raise TypeError("prior must be an instance of BasePrior or None.")

        self.prior = prior
        self._pre_selection: list = []
        self._cross_sectional: list = []
        self._optimizer = None
        self._fallback = None
        self._fallbacks: list = []

    def add_pre_selection(self, transformer) -> StrategyBuilder:
        """Add a pre-selection transformer to the pipeline queue.

        Pre-selection transformers dynamically filter the asset universe
        before the optimizer sees it. They execute before cross-sectional
        transformers in the assembled pipeline.

        Parameters
        ----------
        transformer : skfolio-compatible transformer
            Must implement fit_transform(X). Examples: DropCorrelated,
            SelectNonDominated, SelectComplete.

        Returns
        -------
        StrategyBuilder
            Returns self for method chaining.

        Raises
        ------
        TypeError
            If transformer does not implement fit_transform.
        """
        if not callable(getattr(transformer, "fit_transform", None)):
            raise TypeError("transformer must implement a fit_transform method.")

        self._pre_selection.append(transformer)
        return self

    def add_cross_sectional(self, transformer) -> StrategyBuilder:
        """Add a cross-sectional transformer to the pipeline queue.

        Cross-sectional transformers normalise data row-by-row across the
        asset universe at each point in time. They execute after pre-selection
        transformers and before the optimizer.

        Parameters
        ----------
        transformer : skfolio-compatible transformer
            Must implement fit_transform(X). Examples: CSStandardScaler,
            CSGaussianRankScaler, CSTanhShrinker.

        Returns
        -------
        StrategyBuilder
            Returns self for method chaining.

        Raises
        ------
        TypeError
            If transformer does not implement fit_transform.
        """
        if not callable(getattr(transformer, "fit_transform", None)):
            raise TypeError("transformer must implement a fit_transform method.")

        self._cross_sectional.append(transformer)
        return self

    def set_optimizer(
        self,
        optimizer,
        fallback=None,
        fallbacks: list | None = None,
    ) -> StrategyBuilder:
        """Configure the terminal optimizer for the pipeline.

        Parameters
        ----------
        optimizer : skfolio optimizer
            The primary portfolio optimizer (e.g., MeanRisk, RiskBudgeting,
            HierarchicalRiskParity).
        fallback : skfolio optimizer or None, optional
            A single fallback estimator to attempt if the primary
            optimizer fails. If provided, sets raise_on_failure=False on
            the primary optimizer.
        fallbacks : list or None, optional
            Ordered list of fallback optimizers for backward compatibility.
            If fallback is not explicitly provided and fallbacks is given,
            the first element of fallbacks is used.

        Returns
        -------
        StrategyBuilder
            Returns self for method chaining.

        Raises
        ------
        RuntimeError
            If set_optimizer() is called more than once without reset.
        """
        if self._optimizer is not None:
            raise RuntimeError(
                "set_optimizer() has already been called. "
                "Call .reset() to clear the pipeline configuration before reconfiguring."
            )
        if optimizer is None:
            raise TypeError("optimizer must not be None.")

        resolved_fallback = fallback
        if resolved_fallback is None and fallbacks:
            resolved_fallback = fallbacks[0]

        self._optimizer = _safe_clone(optimizer)
        self._fallback = _safe_clone(resolved_fallback)
        self._fallbacks = [self._fallback] if self._fallback is not None else []

        if self._optimizer is not None:
            if self._fallback is not None:
                if not hasattr(self._optimizer, "raise_on_failure"):
                    raise TypeError(
                        "The provided optimizer does not support fallback semantics."
                    )

                self._optimizer.raise_on_failure = False
                self._optimizer.fallback = self._fallback

            if hasattr(self._optimizer, "linear_constraints"):
                self._optimizer.linear_constraints = list(self.constraints)

        return self

    def reset(self, clear_base_config: bool = False) -> StrategyBuilder:
        """Reset the builder pipeline configuration.

        Clears the transformer queues and optimizer, allowing the builder
        to be reconfigured with new pipeline components. By default, the
        foundational ``constraints`` and ``prior`` supplied at construction
        are retained.

        Parameters
        ----------
        clear_base_config : bool, default False
            If ``True``, also resets ``self.constraints`` to ``[]`` and
            ``self.prior`` to ``None`` in addition to clearing the pipeline
            staging queues.

        Returns
        -------
        StrategyBuilder
            The builder instance for method chaining.
        """
        self._pre_selection = []
        self._cross_sectional = []
        self._optimizer = None
        self._fallback = None
        self._fallbacks = []
        if clear_base_config:
            self.constraints = []
            self.prior = None
        return self

    def build_pipeline(self) -> Pipeline:
        """Assemble all queued transformers and the optimizer into a Pipeline.

        Assembly order (strict):
        1. All pre-selection transformers (in registration order).
        2. All cross-sectional transformers (in registration order).
        3. The configured optimizer (with prior injected if provided).

        Returns
        -------
        sklearn.pipeline.Pipeline

        Raises
        ------
        RuntimeError
            If no optimizer has been set via set_optimizer().
        """
        if self._optimizer is None:
            raise RuntimeError(
                "No optimizer set. Call set_optimizer() before build_pipeline()."
            )

        steps = []
        for i, transformer in enumerate(self._pre_selection):
            steps.append((f"pre_{i}", _safe_clone(transformer)))

        for i, transformer in enumerate(self._cross_sectional):
            steps.append((f"cs_{i}", _safe_clone(transformer)))

        cloned_optimizer = _safe_clone(self._optimizer)
        if self.prior is not None and hasattr(cloned_optimizer, "prior_estimator"):
            cloned_optimizer.prior_estimator = self.prior

        steps.append(("optimizer", cloned_optimizer))

        return Pipeline(steps)

    def build_nco(
        self,
        inner_estimator,
        outer_estimator,
        clusterer: str = "ward",
    ) -> NestedClustersOptimization:
        """Assemble a Nested Clusters Optimisation ensemble.

        Constraints are applied to the inner estimator (within-cluster
        optimisation). The prior (if set) is applied to the outer estimator
        (cross-cluster capital allocation).

        Parameters
        ----------
        inner_estimator : skfolio optimizer
            Optimizes weights within individual clusters.
        outer_estimator : skfolio optimizer
            Allocates capital across clusters using out-of-sample
            cross-validated cluster performance.
        clusterer : str, optional
            Clustering algorithm. One of: "ward", "complete", "single",
            "average", "kmeans". Default is "ward".

        Returns
        -------
        skfolio.optimization.NestedClustersOptimization

        Raises
        ------
        TypeError
            If inner_estimator or outer_estimator is None.
        ValueError
            If clusterer is not one of the permitted values.
        """
        if inner_estimator is None:
            raise TypeError("inner_estimator must not be None.")
        if outer_estimator is None:
            raise TypeError("outer_estimator must not be None.")

        permitted_clusterers = ["ward", "complete", "single", "average", "kmeans"]
        if not isinstance(clusterer, str) or clusterer not in permitted_clusterers:
            raise ValueError(f"clusterer must be one of {permitted_clusterers}")

        cloned_inner = _safe_clone(inner_estimator)
        cloned_outer = _safe_clone(outer_estimator)

        if hasattr(cloned_inner, "linear_constraints"):
            cloned_inner.linear_constraints = list(self.constraints)

        if self.prior is not None and hasattr(cloned_outer, "prior_estimator"):
            cloned_outer.prior_estimator = self.prior

        if clusterer == "kmeans":
            from sklearn.cluster import KMeans

            clustering_estimator = KMeans()
        else:
            from skfolio.cluster import HierarchicalClustering, LinkageMethod

            clustering_estimator = HierarchicalClustering(
                linkage_method=LinkageMethod(clusterer)
            )

        return NestedClustersOptimization(
            inner_estimator=cloned_inner,
            outer_estimator=cloned_outer,
            clustering_estimator=clustering_estimator,
        )
