from __future__ import annotations

from sklearn.pipeline import Pipeline
from skfolio.prior import BasePrior
from skfolio.optimization import NestedClustersOptimization

from flowportfolio.core.universe import Universe

class StrategyBuilder:
    """Assembles skfolio-compatible pipeline estimators for portfolio optimisation.

    Acts as a fluent factory for sklearn.pipeline.Pipeline objects and
    NestedClustersOptimization ensembles. Consumes pre-selection transformers,
    cross-sectional scalers, a prior, and an optimizer, then stitches them
    into a single leak-proof estimator.

    Prefect Compatibility: All build_*() methods are pure functions of
    internal queue state and return serialisable estimator objects.

    Parameters
    ----------
    constraints : list[str]
        Linear constraint strings generated by ConstraintBuilder.build().
        Example: ["core >= 0.50", "satellite <= 0.20"].
    prior : BasePrior or None, optional
        A configured skfolio prior object from PriorSynthesiser.
        If None, the optimizer uses its own internal default prior.

    Raises
    ------
    TypeError
        If constraints is not a list.
    """

    def __init__(
        self,
        constraints: list[str],
        prior: BasePrior | None = None,
    ) -> None:
        if not isinstance(constraints, list):
            raise TypeError("constraints must be a list.")
        
        self.constraints = constraints
        self.prior = prior
        self._pre_selection = []
        self._cross_sectional = []
        self._optimizer = None
        self._fallbacks = []

    def add_pre_selection(self, transformer) -> StrategyBuilder:
        """Add a pre-selection transformer to the pipeline queue.

        Pre-selection transformers dynamically filter the asset universe
        before the optimizer sees it. They execute before cross-sectional
        transformers in the assembled pipeline.

        Parameters
        ----------
        transformer : skfolio-compatible transformer
            Must implement fit_transform(X). Examples: DropCorrelated,
            SelectNonDominated, SelectComplete.

        Returns
        -------
        StrategyBuilder
            Returns self for method chaining.

        Raises
        ------
        TypeError
            If transformer does not implement fit_transform.
        """
        if not hasattr(transformer, "fit_transform") or not callable(getattr(transformer, "fit_transform")):
            raise TypeError("transformer must implement a fit_transform method.")
        
        self._pre_selection.append(transformer)
        return self

    def add_cross_sectional(self, transformer) -> StrategyBuilder:
        """Add a cross-sectional transformer to the pipeline queue.

        Cross-sectional transformers normalise data row-by-row across the
        asset universe at each point in time. They execute after pre-selection
        transformers and before the optimizer.

        Parameters
        ----------
        transformer : skfolio-compatible transformer
            Must implement fit_transform(X). Examples: CSStandardScaler,
            CSGaussianRankScaler, CSTanhShrinker.

        Returns
        -------
        StrategyBuilder
            Returns self for method chaining.

        Raises
        ------
        TypeError
            If transformer does not implement fit_transform.
        """
        if not hasattr(transformer, "fit_transform") or not callable(getattr(transformer, "fit_transform")):
            raise TypeError("transformer must implement a fit_transform method.")
        
        self._cross_sectional.append(transformer)
        return self

    def set_optimizer(
        self,
        optimizer,
        fallbacks: list | None = None,
    ) -> StrategyBuilder:
        """Configure the terminal optimizer for the pipeline.

        Parameters
        ----------
        optimizer : skfolio optimizer
            The primary portfolio optimizer (e.g., MeanRisk, RiskBudgeting,
            HierarchicalRiskParity).
        fallbacks : list or None, optional
            Ordered list of fallback optimizers to attempt if the primary
            optimizer fails. If provided, sets raise_on_failure=False on
            the primary optimizer.

        Returns
        -------
        StrategyBuilder
            Returns self for method chaining.

        Raises
        ------
        RuntimeError
            If set_optimizer() is called more than once without reset.
        """
        if self._optimizer is not None:
            raise RuntimeError("set_optimizer called more than once without resetting.")
            
        self._optimizer = optimizer
        self._fallbacks = fallbacks if fallbacks is not None else []
        
        if self._fallbacks:
            setattr(self._optimizer, "raise_on_failure", False)
            setattr(self._optimizer, "fallback", self._fallbacks[0])
            
        if hasattr(self._optimizer, "linear_constraints"):
            self._optimizer.linear_constraints = self.constraints
            
        return self

    def build_pipeline(self) -> Pipeline:
        """Assemble all queued transformers and the optimizer into a Pipeline.

        Assembly order (strict):
        1. All pre-selection transformers (in registration order).
        2. All cross-sectional transformers (in registration order).
        3. The configured optimizer (with prior injected if provided).

        Returns
        -------
        sklearn.pipeline.Pipeline

        Raises
        ------
        RuntimeError
            If no optimizer has been set via set_optimizer().
        """
        if self._optimizer is None:
            raise RuntimeError("No optimizer set. Call set_optimizer() before build_pipeline().")
            
        steps = []
        for i, transformer in enumerate(self._pre_selection):
            steps.append((f"pre_{i}", transformer))
            
        for i, transformer in enumerate(self._cross_sectional):
            steps.append((f"cs_{i}", transformer))
            
        if self.prior is not None and hasattr(self._optimizer, "prior_estimator"):
            self._optimizer.prior_estimator = self.prior
            
        steps.append(("optimizer", self._optimizer))
        
        return Pipeline(steps)

    def build_nco(
        self,
        inner_estimator,
        outer_estimator,
        clusterer: str = "ward",
    ) -> NestedClustersOptimization:
        """Assemble a Nested Clusters Optimisation ensemble.

        Constraints are applied to the inner estimator (within-cluster
        optimisation). The prior (if set) is applied to the outer estimator
        (cross-cluster capital allocation).

        Parameters
        ----------
        inner_estimator : skfolio optimizer
            Optimizes weights within individual clusters.
        outer_estimator : skfolio optimizer
            Allocates capital across clusters using out-of-sample
            cross-validated cluster performance.
        clusterer : str, optional
            Clustering algorithm. One of: "ward", "complete", "single",
            "average", "kmeans". Default is "ward".

        Returns
        -------
        skfolio.optimization.NestedClustersOptimization

        Raises
        ------
        ValueError
            If clusterer is not one of the permitted values.
        """
        permitted_clusterers = ["ward", "complete", "single", "average", "kmeans"]
        if clusterer not in permitted_clusterers:
            raise ValueError(f"clusterer must be one of {permitted_clusterers}")
            
        if hasattr(inner_estimator, "linear_constraints"):
            inner_estimator.linear_constraints = self.constraints
            
        if self.prior is not None and hasattr(outer_estimator, "prior_estimator"):
            outer_estimator.prior_estimator = self.prior
            
        if clusterer == "kmeans":
            from sklearn.cluster import KMeans
            clustering_estimator = KMeans()
        else:
            from skfolio.cluster import HierarchicalClustering, LinkageMethod
            clustering_estimator = HierarchicalClustering(linkage_method=LinkageMethod(clusterer))
            
        return NestedClustersOptimization(
            inner_estimator=inner_estimator,
            outer_estimator=outer_estimator,
            clustering_estimator=clustering_estimator
        )
